services:
  # PHP Service
  tinyurl_api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: tinyurl_api
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app
    networks:
      - tinyurl
    depends_on:
      - mysql

  tinyurl_queue:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: tinyurl_queue
    command: ["php", "artisan", "queue:work"]
    restart: unless-stopped
    tty: true
    expose:
      - "9001"
    volumes:
      - .:/var/www/app
    networks:
      - tinyurl
    depends_on:
      - mysql

  # MySQL Service
  mysql:
    image: mysql/mysql-server:latest
    ports:
        - '3306:3306'
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD} 
      MYSQL_ROOT_HOST: '%' # Allow remote access
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - tinyurl

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7001:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app:delegated
    depends_on:
      - tinyurl_api
    networks:
      - tinyurl

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - tinyurl

networks:
  tinyurl:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local